[package]
name = "rust-lox"
version = "0.1.0"
authors = ["AnsonH <ansonheung2000@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
anyhow = "1.0.68"                                # error handling
bytes = "1.3.0"                                  # helps manage buffers
miette = { version = "7.2.0", features = ["fancy"] }    # fancy errors
thiserror = "1.0.38"                             # error handling
